services:
  calles-posadas:
    image: ghcr.io/gruposim/calles-posadas:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calles-posadas
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calles-posadas.rule=Host(`posadas.ferchamorro.cloud`)"
      - "traefik.http.routers.calles-posadas.entrypoints=websecure"
      - "traefik.http.routers.calles-posadas.tls=true"
      - "traefik.http.routers.calles-posadas.tls.certresolver=letsencrypt"
      - "traefik.http.services.calles-posadas.loadbalancer.server.port=3000"
    networks:
      - pigar-staging_edge

networks:
  pigar-staging_edge:
    external: true
